### ISSUE TITLE
chai should issues

### ISSUE THREAD

**Issue by beckend** [speedskater/babel-plugin-rewire#140] opened 2016-06-20 17:17 UTC
```javascript
import imageResolver from './img-resolver';

const should = chai.should();
describe('ImageResolver', () => {
  it('should throw an error using on browser', () => {
    try {
      imageResolver();
    } catch (error) {
      should.exist(error);
    }
  });
});
```
Object is not a constructor (evaluating '_get__('should').exist(error)')

It works fine without rewire.

**Comment by StyMaar** [comment] 2016-06-22 09:47
it looks like a duplicate of #115 

As a work-around you can try to name your constant `_should` instead of `should`. This should fix the issue until #115 is solved.

**Comment by speedskater** [comment] 2016-06-27 14:10
Fixed the issue in course of fixing #115. Added test which explicitly checks support of chai should.

**Closed by speedskater** 2016-06-27 14:10 UTC
