### ISSUE TITLE
TypeError: Cannot assign to read only property '__get__' of object '#<Object>'

### ISSUE THREAD

**Issue by yvele** [speedskater/babel-plugin-rewire#163] opened 2016-09-26 11:19 UTC
# Problem

I get the following error using `babel-plugin-rewire@1.0.0` and `node@6.3.0`

``` none
/Users/me/project/lib/MyClass.js:181
exports.__get__ = _get__2("_get__");
                ^

TypeError: Cannot assign to read only property '__get__' of object '#<Object>'
```

Related to https://github.com/speedskater/babel-plugin-rewire/issues/133 (which is closed)
# Source code

MyClass.js

``` js
const BAR = "bar";

export default class MyClass {
  foo() {
    return BAR;
  }
}
```

.babelrc (`babel-cli@6.14.0`)

``` json
{
  "presets": ["latest"],
  "env": {
    "test": {
      "plugins": ["rewire"]
    }
  }
}
```
# Behaviour

Actually, rewire exports are made **after** default export :

``` js
exports.default = MyClass;

....

exports.__get__ = _get__;
exports.__GetDependency__ = _get__;
exports.__Rewire__ = _set__;
exports.__set__ = _set__;
exports.__ResetDependency__ = _reset__;
exports.__RewireAPI__ = _RewireAPI__;
```

Rewire exports should be **before** default export :

``` js

....

exports.__get__ = _get__;
exports.__GetDependency__ = _get__;
exports.__Rewire__ = _set__;
exports.__set__ = _set__;
exports.__ResetDependency__ = _reset__;
exports.__RewireAPI__ = _RewireAPI__;

exports.default = MyClass;
```

(or something like that...)
# Workaround

Not using `default`...  :confused:

MyClass.js

``` js
const BAR = "bar";

export class MyClass {
  foo() {
    return BAR;
  }
}
```

**Comment by speedskater** [comment] 2016-10-10 13:11
@yvele thanks for providing the sample. I have added a sample (https://github.com/speedskater/babel-plugin-rewire/tree/master/samples/issue163) for your issue, but was not able to reproduce your issue. Could you please have a look at the sample and let me know whether it runs on your system?

**Comment by speedskater** [comment] 2016-11-09 08:58
@yvele anything  new from your side?

**Comment by yvele** [comment] 2016-11-09 09:26
@speedskater Sorry I'm not using `babel-plugin-rewire` anymore in my projects :persevere:

**Comment by speedskater** [comment] 2016-11-09 09:37
@yvele sorry to hear that. As i am not able to reproduce your error I will close this issue for now.

**Closed by speedskater** 2016-11-09 09:37 UTC

**Comment by ydaniv** [comment] 2017-05-11 20:57
Getting the same issue on version `1.1.0` and `node@7.10.0`. Removing `default` doesn't seem to solve it. Any idea?

**Comment by emerson-h** [comment] 2017-06-29 18:48
I can confirm that tis is an issue with 1.0.0 and Node 7.9.0 as well.
