### ISSUE TITLE
Unexpected token 'var' with switch statement 

### ISSUE THREAD

**Issue by jhollingworth** [speedskater/babel-plugin-rewire#100] opened 2016-02-15 13:51 UTC
I've come across an odd edge case with switch statements where the parse will throw "Unexpected token var" (Potentially related to #4)

```
class Foo { }

// Returns "SyntaxError: Unexpected token var"
function createComponent (type) {
  switch (type) {
    case 'foo': return <Foo />
    case 'bar': return <Bar />
  }
}

// OK
function createComponent (type) {
  switch (type) {
    case 'foo': {
      return <Foo />
    }
    case 'bar': return <Bar />
  }
}
```

Versions:

* babel-core: ^6.3.15
* babel-loader: ^6.2.0
* babel-preset-es2015: ^6.3.13
* babel-preset-react: ^6.3.13
* babel-runtime: ^6.3.19

**Comment by TheSavior** [comment] 2016-02-15 17:04
Looks like a duplicate of https://github.com/speedskater/babel-plugin-rewire/issues/92

**Comment by speedskater** [comment] 2016-03-06 09:45
@jhollingworth, @TheSavior seems for me too, that this is a duplicate. As the issue was just fixed and will be featured in the RC1 which will be published today. I will close this issue for now.

**Closed by speedskater** 2016-03-06 09:45 UTC

**Comment by jhollingworth** [comment] 2016-03-06 10:02
:+1: thanks
