### ISSUE TITLE
Cannot rewire jsx dependencies

### ISSUE THREAD

**Issue by ssurana** [speedskater/babel-plugin-rewire#82] opened 2015-12-15 19:19 UTC
When using webpack + karma+ babel and react components in .jsx file. Rewiring dependencies is not working;

ChildComponent.jsx
```javascript

import React from 'react';

class ChildComponent extends React.Component {
    render() {
        return (
            <div>
                          i am child component
            </div>
        );
    }
};

```

ParentComponent.jsx
```javascript

import React from 'react';
import ChildComponent from './ChildComponent.jsx';

class ParentComponent extends React.Component {
    render() {
        
        return (
            <div>
                <ChildComponent />
            </div>
        );
    }
};

```

testSpec.jsx
```javascript

import React from 'react';
import ReactDOM from 'react-dom';
import ReactTestUtils from 'react-addons-test-utils';

import ParentComponent from './ParentComponent.jsx';


class MockComponent extends React.Component {
    render() {
        return (
            <div>Mock</div>
        );
    } 
};

describe('ParentComponent Test', function() {
    beforeEach(function() {
       
       ParentComponent.__Rewire__('ChildComponent', MockComponent);
       this.component = ReactTestUtils.renderIntoDocument(<ParentComponent />);
    });

    it('should use mock component', function() { 
        var div = ReactTestUtils.findRenderedDOMComponentsWithTag(this.component, 'div');
        console.log(div);
        expect(div.textContent).toEqual('Mock');
    });
    
    afterEach(function() {
       ParentComponent.__ResetDependency__('MockComponent');
    });
});

```

karma.conf.js
```javascript
// Karma configuration
// Generated on Wed Dec 09 2015 16:44:22 GMT-0500 (Eastern Standard Time)

module.exports = function(config) {
  config.set({

    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: '',


    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: ['jasmine'],


    // list of files / patterns to load in the browser
    files: [
      'tests.webpack.js'
    ],


    // list of files to exclude
    exclude: [
    ],


    // preprocess matching files before serving them to the browser
    // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
    preprocessors: {
      'tests.webpack.js': ['webpack', 'sourcemap'],
    },


    webpack: {
      devtool: 'source-map',
      module: {
            loaders: [
            {
                test: /\.jsx?$/,
                loader: 'babel-loader',
                exclude: /node_modules/,
                query: {
                    presets: ['es2015', 'react'],
                    plugins: ['babel-plugin-rewire']
                }
            }
            ]
        }
    },
    
    webpackMiddleware: {
      noInfo: true
    },
    
    browserNoActivityTimeout: 60000,
    
    plugins: [
      'karma-jasmine',
      'karma-phantomjs-launcher',
      'karma-webpack',
      'karma-sourcemap-loader',
      'karma-spec-reporter'
    ],
    
    // test results reporter to use
    // possible values: 'dots', 'progress'
    // available reporters: https://npmjs.org/browse/keyword/karma-reporter
    reporters: ['spec'],


    // web server port
    port: 9876,


    // enable / disable colors in the output (reporters and logs)
    colors: true,


    // level of logging
    // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.LOG_INFO,


    // enable / disable watching file and executing tests whenever any file changes
    autoWatch: true,


    // start these browsers
    // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
    browsers: ['PhantomJS'],


    // Continuous Integration mode
    // if true, Karma captures browsers, runs the tests and exits
    singleRun: false,

    // Concurrency level
    // how many browser should be started simultanous
    concurrency: Infinity
  })
}


```

**Comment by rnicholus** [comment] 2015-12-16 04:00
I'm seeing the same issue, plus a number of other bugs that have appeared since the update to babel 6. In some cases, modules imported into a JSX file are rewired properly, and others are simply not rewired. This was all working fine pre-Babel 6 and pre-1.0.

**Comment by speedskater** [comment] 2015-12-16 12:08
@rnicholus , @ssurana thanks for reporting the issues. Could you create PRs for cases when it fails. I will try to tackle these scenarios on monday and create a new beta then.

**Comment by rnicholus** [comment] 2015-12-17 03:19
I suspect it would take me far longer than yourself to track down the specific issue in this library. However, I can offer a _very_ simple test case:

Component to test:
```javascript
import React from 'react'
import TempTest from './temp-test'

export default class Foo extends React.Component {
    render() {
        return (
            <div className="content">
                <TempTest/>
            </div>
        )
    }
}
```

The test:
```javascript
import React from 'react'
import ReactDom from 'react-dom'
import TestUtils from 'react/lib/ReactTestUtils'
import Foo from 'hello-world/foo'

describe('foo tests', () => {
    beforeEach(() => {
        Foo.__Rewire__('TempTest', class extends React.Component {
            render() {
                return <div>test</div>
            }
        })
    })


    it('test', () => {
        var foo = TestUtils.renderIntoDocument(<Foo/>),
            component = TestUtils.findRenderedDOMComponentWithClass(foo, 'content')

        console.log(component.textContent)
    })
})
```

Actual output of the test:
> 'default'

Expected output of the test:
> 'test'

Relevant portion of package.json (dependencies):
```json
"dependencies": {
    "babel-polyfill": "6.3.14",
    "babel-runtime": "6.3.19",
    "babel-cli": "6.3.17",
    "babel-core": "6.3.17",
    "babel-loader": "6.2.0",
    "babel-plugin-rewire": "1.0.0-beta-3",
    "babel-plugin-transform-decorators-legacy": "1.3.1",
    "babel-preset-es2015": "6.3.13",
    "babel-preset-react": "6.3.13",
    "babel-preset-stage-0": "6.3.13",
}
```

Webpack loader entry:
```javascript
{
    test: /\.js/,
    loader: 'babel',
    exclude: /node_modules/,
    query: {
        plugins: ['transform-decorators-legacy'],
        presets: ['es2015', 'react', 'stage-0']
    }
}
```

Top of karma config, where rewire plugin is added before tests are run:
```javascript
var webpackConfig = require('./webpack.config')

webpackConfig.module.loaders[0].query.plugins.push('rewire')
```


This was all working beautifully pre Babel-6 and pre Rewire 1.x.

**Comment by speedskater** [comment] 2015-12-21 14:27
@rnicholus, @ssurana thanks for the reporting and the example. I converted it into a unit test sample so it should always be checked in the future.

**Comment by rnicholus** [comment] 2015-12-21 14:28
@speedskater - Thanks for this ! I'd love to test out this fix, but would prefer it be offered in a beta4 release. Do you plan on pushing a new beta to npm?

**Comment by speedskater** [comment] 2015-12-21 14:34
@rnicholus I am fixing some further issues and will release a new beta today. Please have a look at https://gitter.im/speedskater/babel-plugin-rewire?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge. I will post a message as soon as a new beta is available.

**Comment by jayfunk** [comment] 2016-01-04 19:42
Any updates on this fix being in a release? I am running in the same issue.

**Comment by adamdicarlo** [comment] 2016-01-05 18:00
Also ran into this issue. At least when the top-level var is used as JSX component (`<Thing />`), it does not get rewired. I checked the generated code.

**Comment by adamdicarlo** [comment] 2016-01-05 19:29
There's a commit on master that looks like was intended to fix this bug, but it seems to make it worse for me:
```
WARNING in ./src/features/foo/settings-bar.jsx
Module build failed: TypeError: /Users/.../src/features/foo/settings-bar.jsx: Property children[0] of JSXElement expected node to be of a type ["StringLiteral","JSXExpressionContainer","JSXElement"] but instead got "JSXText"
    at validate (/Users/.../node_modules/babel-types/lib/definitions/index.js:101:13)
    at validator (/Users/.../node_modules/babel-types/lib/definitions/index.js:49:7)
    at Object.validate (/Users/.../node_modules/babel-types/lib/definitions/index.js:182:10)
    at validate (/Users/.../node_modules/babel-types/lib/index.js:268:9)
    at Object.builder (/Users/.../node_modules/babel-types/lib/index.js:221:7)
    at RewireState.JSXElement (/Users/.../node_modules/babel-plugin-rewire/lib/babel-plugin-rewire.js:52:54)
    at NodePath._call (/Users/.../node_modules/babel-traverse/lib/path/context.js:74:18)
    at NodePath.call (/Users/.../node_modules/babel-traverse/lib/path/context.js:46:17)
    at NodePath.visit (/Users/.../node_modules/babel-traverse/lib/path/context.js:104:12)
    at TraversalContext.visitQueue (/Users/.../node_modules/babel-traverse/lib/context.js:153:16)
    at TraversalContext.visitMultiple (/Users/.../node_modules/babel-traverse/lib/context.js:108:17)
    at TraversalContext.visit (/Users/.../node_modules/babel-traverse/lib/context.js:195:19)
    at Function.traverse.node (/Users/.../node_modules/babel-traverse/lib/index.js:139:17)
    at NodePath.visit (/Users/.../node_modules/babel-traverse/lib/path/context.js:114:22)
    at TraversalContext.visitQueue (/Users/.../node_modules/babel-traverse/lib/context.js:153:16)
    at TraversalContext.visitMultiple (/Users/.../node_modules/babel-traverse/lib/context.js:108:17)
    at TraversalContext.visit (/Users/.../node_modules/babel-traverse/lib/context.js:195:19)
    at Function.traverse.node (/Users/.../node_modules/babel-traverse/lib/index.js:139:17)
 @ ./src \.jsx?
```

Work around I'm using for now is to alias the top-level variable inside the render function:

```
// Module that needs to have 'Component' rewired
import Component from './Component'

class Thing {
  render () {
    const _Component = Component
    return <_Component />
  }
}
```

**Comment by speedskater** [comment] 2016-01-05 22:30
I will have a short look at this issue tomorrow and will hopefully be able to ship a new beta then. If not I am doing an extended babel-plugin-rewire session on monday.

**Comment by speedskater** [comment] 2016-01-06 19:56
@ssurana @rnicholus @jayfunk @adamdicarlo Shipped a new beta 1.0.0-beta-4. Please let me know if it works for you. If any of you can confirm that this bug is fixed blease close this issue.

**Comment by rnicholus** [comment] 2016-01-07 07:17
@speedskater This new version appears to cause new issues. In fact, I can't even compile my app with webpack/babel anymore. Downgrading to beta3 allows me to at least generate webpack bundles with babel.

Here's an example of a new error I'm seeing:

```bash
ERROR in ./app/hello-world/index.jsx
Module build failed: TypeError: /Users/rnicholus/code/project/app/hello-world/index.jsx: Property body[1] of BlockStatement expected node to be of a type ["Statement"] but instead got "JSXElement"
    at validate (/Users/rnicholus/code/project/node_modules/babel-types/lib/definitions/index.js:101:13)
    at validator (/Users/rnicholus/code/project/node_modules/babel-types/lib/definitions/index.js:49:7)
    at Object.validate (/Users/rnicholus/code/project/node_modules/babel-types/lib/definitions/index.js:182:10)
    at validate (/Users/rnicholus/code/project/node_modules/babel-types/lib/index.js:268:9)
    at Object.builder (/Users/rnicholus/code/project/node_modules/babel-types/lib/index.js:221:7)
    at NodePath.replaceExpressionWithStatements (/Users/rnicholus/code/project/node_modules/babel-traverse/lib/path/replacement.js:238:54)
    at NodePath.insertBefore (/Users/rnicholus/code/project/node_modules/babel-traverse/lib/path/modification.js:51:10)
    at RewireState.JSXElement (/Users/rnicholus/code/project/node_modules/babel-plugin-rewire/lib/babel-plugin-rewire.js:47:21)
    at NodePath._call (/Users/rnicholus/code/project/node_modules/babel-traverse/lib/path/context.js:74:18)
    at NodePath.call (/Users/rnicholus/code/project/node_modules/babel-traverse/lib/path/context.js:46:17)
    at NodePath.visit (/Users/rnicholus/code/project/node_modules/babel-traverse/lib/path/context.js:104:12)
    at TraversalContext.visitQueue (/Users/rnicholus/code/project/node_modules/babel-traverse/lib/context.js:153:16)
    at TraversalContext.visitSingle (/Users/rnicholus/code/project/node_modules/babel-traverse/lib/context.js:113:19)
    at TraversalContext.visit (/Users/rnicholus/code/project/node_modules/babel-traverse/lib/context.js:197:19)
    at Function.traverse.node (/Users/rnicholus/code/project/node_modules/babel-traverse/lib/index.js:139:17)
    at NodePath.visit (/Users/rnicholus/code/project/node_modules/babel-traverse/lib/path/context.js:114:22)
    at TraversalContext.visitQueue (/Users/rnicholus/code/project/node_modules/babel-traverse/lib/context.js:153:16)
 @ ./app/hello-world/init.jsx 9:677-689
```

I'm seeing _a lot_ of similar errors.

**Comment by speedskater** [comment] 2016-01-07 07:53
@rnicholus thanks for testing. Could you please provide the corresponding index.jsx file?

**Comment by rnicholus** [comment] 2016-01-07 09:18
@speedskater I've updated my comment to include the code from index.jsx.

**Comment by speedskater** [comment] 2016-01-07 09:53
@rnicholus thanks for the sample. I will have a look at it asap (latest on monday).

**Closed** 2016-01-11 10:22 UTC

**Comment by speedskater** [comment] 2016-01-11 10:24
The problem is fixed. I will publish beta 5 today in the afternoon. Have a look at the gitter chat when the new version is pushed.

**Comment by rnicholus** [comment] 2016-01-19 04:49
Beta5 fixes the original issue and does not create any new issues, as far as I can tell. Seems to be ready for 1.1.0 to me.
