### ISSUE TITLE
Question about Keeping Up With Babel / Suggestion / Maintenance 

### ISSUE THREAD

**Issue by damassi** [speedskater/babel-plugin-rewire#41] opened 2015-08-12 17:09 UTC
This is in no way a criticism of your work, but I'm wondering if there is a reason this plugin seems to break so frequently?  Is it because Babel is constantly changing how it handles things / API?  There have been numerous "OMG!" moments lately where a deploy has broke due to babel-plugin-rewire, and it would be nice to either:

A) Mention the general API instability in the README, or perhaps think of another approach?  Or 
B) **LIMIT** the scope of this plugins reach similar to how the original Rewire does it:

```javascript
var rewire = require('rewire');
var ClassToChange = rewire('path/to/file');  
```

That way we're only worrying about certain areas of the app rather than attaching additional exports to every single module (which seems largely incorrect to me) which will break everything, rather than just tests.  

Commentary appreciated.

**Comment by TheSavior** [comment] 2015-08-12 17:13
@damassi This package has changed a lot in the last week or two because we've been trying to get it functionally useful and have been changing how we attach and inject the getters and setters. For example, we needed to use `Object.defineProperty` instead of setting the functions on the export directly using `=` which had some unintended side effects. 

I would imagine once these things settle down, which seems like it is going to happen pretty soon, then `babel-plugin-rewire` will be bumped to 1.0.0 and be much more stable.

**Comment by damassi** [comment] 2015-08-12 17:15
Thats great to hear :)  I'll watch the repo and look out for a 1.0 release.

**Comment by speedskater** [comment] 2015-08-12 21:23
@damassi. Thanks for your feedback. And thanks to @TheSavior for the quick response. 
I am fully aware that over the last weeks babel-plugin-rewire was constantly breaking. We therefore increased the tests and added samples and usage tests (https://travis-ci.org/speedskater/babel-plugin-rewire).

As mentioned by TheSavior, in terms of features rewiring of variables, functions named exports and an additonal APIObject  was added. Furthermore many bug fixes were added to increase the stability (like improved CommonJS support and interoperability). Unfortunately some regressions occurred while improving the plugin. 

We hope that in the future we can further improve stability. Although, as babel is a rather new project as well, there might be some changes which could break babel-plugin-rewire as well. In such cases we will try to adept the plugin as soon as possible. 

So if you have use cases which are currently failing we would really appreciate to hear from you. 
If you have samples which are currently not covered by our tests it would be great if you could provide a PR containing those samples.

Regarding your request to Limit the scope I would suggest to add the plugin only in case of unit tests. Furthermore you can apply the plugin only to a limited amount of your files. 
Although, the goal of babel-plugin-rewire is to not change the semantics of the transformed files. Hence, if you have an example where this is the case please open an issue and we will try to provide a solution.

Overall our goal is to provide a stable solution (which is our goal too, as we use it more and more for our own unit tests).

**Comment by speedskater** [comment] 2016-03-06 10:19
I will close this issue for now.

**Closed by speedskater** 2016-03-06 10:19 UTC
