### ISSUE TITLE
Works with require() and doesn't work with import

### ISSUE THREAD

**Issue by apedyashev** [speedskater/babel-plugin-rewire#130] opened 2016-05-13 17:23 UTC
It seems that Loader can be rewired only if tested component uses require() instead of ES6's *import*
```javascript
import Loader from 'components/Loader'; // test fails when the Loader is imported
// test passes when the Loader is required
// let Loader = require('components/Loader');

class HomePage extends React.Component {
  render() {
    return (<div><Loader /></div>);
  }
}

export {HomePage}
```

test:
```javascript
import  {HomePage, __RewireAPI__ as HomePageRewireApi} from 'path/to/HomePage';

class PageLoaderMock extends React.Component {
  render() {
    return (<div>loader mock</div>);
  }
}

describe('Page', () => {
  it('displays Loader', () => {
    let renderer = TestUtils.createRenderer();
    HomePageRewireApi.__Rewire__('Loader', PageLoaderMock);

    renderer.render( <HomePage  /> );
    let output = renderer.getRenderOutput();

    expect(output.props.children.type).to.be.equal(PageLoaderMock);
  });
});
```

**Comment by wangpin34** [comment] 2016-06-04 13:34
Same issue when I try to mock a module

ErrorHandler.js
```
import { FileError, Default } from './Constants'
import Logger from './Logger'

export default class ErrorHandler {

    static on( error, action ) {...}

}
```

ErrorHandler.test.js
```
import { expect } from 'chai'
import sinon from 'sinon'
import ErrorHandler from '../src/ErrorHandler'


describe('Test Class ErrorHandler', () => {

	let log

	before(() => {

		log = sinon.spy()

		ErrorHandler.__Rewire__('Logger', {
			newInstance() {
				return {
					log: log
				}
			}
		})
	})
	
	describe('Test static method generate',() => {

		it('log should be called', () => {
			ErrorHandler.on({code:2},'Test:')
			expect(log.called).to.be.ok
		})
	})

})
```

**Comment by frederikb** [comment] 2016-06-16 14:25
I've seem to have run into the same issue as @apedyashev. The plugin generally works for other use cases, however ES6 type imports cannot be mocked. Is this a known or expected limitation?

**Comment by speedskater** [comment] 2016-06-27 15:12
@frederikb @apedyashev @wangpin34 Generally rewiring of es6 modules should work as this is the intended use case of this library. I have added the test case of apedyashev to the samples and was not able to reproduce your error. Please see issue130-jsx-es6-type-imports in the samples directory. 

Maybe it is related to the way you load modules. What is the module loader you are using?

**Comment by jmarceli** [comment] 2016-07-15 13:50
I was having same issue but after looking once more at https://github.com/speedskater/babel-plugin-rewire#test-code-3 I found mistake in my code.

For @apedyashev test code should (probably look like this because there is no default export):
```
import  HomePageRewireApi, {HomePage} from 'path/to/HomePage'; // the change is here

// remaining test code
```

and for @wangpin34 (because there is default export):
```
import { expect } from 'chai'
import sinon from 'sinon'
import ErrorHandler, { __RewireAPI__ as rewireAPI } from '../src/ErrorHandler' // the change is here

describe('Test Class ErrorHandler', () => {

    let log

    before(() => {

        log = sinon.spy()

        rewireAPI.__Rewire__('Logger', { // the change is here
            newInstance() {
                return {
                    log: log
                }
            }
        })
    })

    ...
})
```
I might be wrong but this was my case.

**Comment by speedskater** [comment] 2016-08-29 09:11
@all. Sorry the delay on this issue. and thanks @jmarceli for helping out. Hence, I will close this issue for now. @wangpin34, @frederikb @apedyashev If the comment from @jmarceli did not work for you please do not hesitate to reopen this bug and provide a detailed example of your issues.

**Closed by speedskater** 2016-08-29 09:11 UTC

**Comment by chemoish** [comment] 2016-12-28 02:50
@jmarceli `import  HomePageRewireApi, {HomePage} from 'path/to/HomePage';` that doesn't look right? I don't see a `default` export in his example? Nor do I see a reference to `__RewireAPI__`?

@speedskater I am having a similar problem as @apedyashev and i suspect it has to do with `isparta` or `webpack`, since my tests are running fine without `isparta`. The only slight difference in my example is that `Loader` is a named export.

Are you saying that https://github.com/speedskater/babel-plugin-rewire/blob/master/samples/issue130-jsx-es6-type-imports/sample.js should work as specified?

(mine also works with `require` instead of `import`)

**Comment by speedskater** [comment] 2016-12-28 08:14
@chemoish thanks for reporting your findings here. I would suggest to use babel-istanbul as imho it integrates much nicer into the babel workflow.
