### ISSUE TITLE
Return reset function (like rewire)?

### ISSUE THREAD

**Issue by StevenLangbroek** [speedskater/babel-plugin-rewire#26] opened 2015-08-04 14:37 UTC
I prefer to keep cleanup-code out of my actual specs, and thought maybe it would be possible to return a "restore" function from `__Rewire__` like the original rewire does?

```js
var revert = myModule.__set__("port", 3000);

// port is now 3000
revert();
// port is now the previous value
```

**Comment by speedskater** [comment] 2015-08-04 17:52
Thanks for your input. Do you explicitly need this? 
Would something like this be suitable for you as well (I use it in my tests). If you are interested i could opensource it as a utility library. 

```js
describe('MyTestSuite', function() {
  //adds an afterEach handler to the suite and therefore resets your module after each test
  var rewire = enableRewire();

  it('myTest', function() {
   rewire(myModule, 'port', 3000);
   .... testcode ...
  });
});
```

**Comment by StevenLangbroek** [comment] 2015-08-05 08:26
Yeah absolutely. Whatever works. At this point I'm not tied into a specific solution, but I don't want cleanup to be in my individual specs :).

**Comment by speedskater** [comment] 2015-08-07 21:43
Okay. Therefore, I will create a project for the mentioned helper library. But it will take till about mid of next week.

**Comment by TheSavior** [comment] 2015-08-10 18:40
We should try to match the rewire interface as much as possible

**Comment by speedskater** [comment] 2015-08-11 07:16
@TheSavior I agree. But I think we should generate as little code as needed because detecting errors in library code is much simpler and straightforward than in generated intermediate code.

**Comment by nathanjd** [comment] 2015-10-13 19:08
I would love to see this and support for an object parameter to dependency reassignment. For example:

let revert = myModule.__Rewire__({
    dependency1name: dependency1mock,
    dependency2name: dependency2mock
});

revert();

**Comment by speedskater** [comment] 2015-11-27 07:25
@nathanjd @StevenLangbroek it took longer than initially expected but there is a new beta 1.0.0-beta-2 for babel 6 which contains rewire.js style __with__ functionality. Could you please test it and if you have any issues with it could you please provide a PR with a minimal sample reproducing your error (analog to the samples in the repo used by https://github.com/speedskater/babel-plugin-rewire/blob/master/usage-tests/BabelRewirePluginUsageTest.js.

**Closed** 2016-01-06 12:08 UTC
